def skipRemainingStages = true

pipeline {
    agent any

    triggers {
        // GitLab Webhook을 통해 backend 브랜치로의 push 이벤트 시 트리거.
        gitlab(
            triggerOnPush: true,
        )
    }

    environment {
        SERVER_PORT = '8080'
        SERVER_NAME = 'scg'
        EC2_IP = credentials('k11c206_IP')
        SSH_INFO = credentials('k11c206_SSH')
    }

    stages {

        stage('Checkout Code') {
            steps {
                // backend 브랜치의 accompanyboard 폴더만 체크아웃
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/develop']],
                    userRemoteConfigs: [[
                        url: 'https://lab.ssafy.com/s11-final/S11P31C206.git',
                        credentialsId: 'GitLab_Personal_Access_Token'
                    ]],
                    extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: "${SERVER_NAME}/"]]]]
                ])
            }
        }

        stage('Build Docker Image') {
            when {
                changeset "edith-back/${SERVER_NAME}/**"
            }
            steps {
                script {
                    skipRemainingStages = false
                    sh """
                    cd edith-back/${SERVER_NAME}
                    chmod +x ./gradlew
                    ./gradlew build
                    ls build/libs
                    docker build -t ${SERVER_NAME}:latest .
                    """
                }
            }
        }

        // stage('Login to Docker Registry') {
        //     when {
        //         changeset "edith-back/${SERVER_NAME}/**"
        //     }
        //     steps {
        //         script {
        //             sh """
        //             docker login -u $DOCKER_USERINFO_USR -p $DOCKER_USERINFO_PSW
        //             """
        //         }
        //     }
        // }

        // stage('Push Docker Image to Repository') {
        //     when {
        //         changeset "edith-back/${SERVER_NAME}/**"
        //     }
        //     steps {
        //         script {
        //             sh """
        //             docker tag ${SERVER_NAME}:latest $DOCKER_REPO_USR/$DOCKER_REPO_PSW:${SERVER_NAME}-latest
        //             docker push $DOCKER_REPO_USR/$DOCKER_REPO_PSW:${SERVER_NAME}-latest
        //             """
        //         }
        //     }
        // }

        stage('Deploy to EC2') {
            when {
                changeset "edith-back/${SERVER_NAME}/**"
            }
            steps {
                script {
                    sh """
                    ssh -o StrictHostKeyChecking=no -i $SSH_INFO $SSH_INFO_USR@$EC2_IP <<-EOF
                    docker stop ${SERVER_NAME} || true
                    docker rm ${SERVER_NAME} || true
                    docker rmi ${SERVER_NAME}:latest || true
                    docker system prune -f --volumes
                    docker pull ${SERVER_NAME}:latest
                    docker run -it -d --name ${SERVER_NAME} -p $SERVER_PORT:$SERVER_PORT ${SERVER_NAME}:latest
                    EOF
                    """.stripIndent()
                }
            }
        }

        // stage('Logout from Docker Registry') {
        //     when {
        //         changeset "edith-back/${SERVER_NAME}/**"
        //     }
        //     steps {
        //         script {
        //             sh """
        //             docker logout
        //             """
        //         }
        //     }
        // }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
        success {
            script{
                if (skipRemainingStages) {
                    echo "No changes in ${SERVER_NAME} folder, skipping build and deploy."
                } else {
                    echo "Deployed successfully on port ${SERVER_PORT}!"
                    def user = sh(script: 'git log -1 --pretty=format:"%an"', returnStdout: true).trim()
                    mattermostSend (
                        color: 'good',
                        message: "${user}님의 ${env.JOB_NAME} 서버 배포 성공. (#${env.BUILD_NUMBER}) ",
                    )
                }
            }
        }
        failure {
            echo 'Deployment failed!'
            script{
                def user = sh(script: 'git log -1 --pretty=format:"%an"', returnStdout: true).trim()
                mattermostSend (
                    color: 'danger',
                    message: "${user}님? ${env.JOB_NAME} 서버 터졌는데요? (#${env.BUILD_NUMBER}) ",
                )
            }
        }
    }
}